name: Mettre à jour README

on:
  schedule:
    - cron: '0 0 * * *' # tous les jours à minuit
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Installer requests
        run: pip install requests

      - name: Mettre à jour README
        run: python update_readme.py

      - name: Commit & push README mis à jour
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Mise à jour automatique des projets" || echo "Rien à commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
